project:
  type: website  
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!slides/"
    - "!_ing"
  preview:
    port: 3000
    browser: false    

website:
  title: "F# with -sd-"
  description: "Let's learn F# together!"
  twitter-card: true
  open-graph: true
  page-navigation: true  
  navbar:
    background: primary
    search: true
  sidebar:
    style: "floating"
    contents:
      - index.qmd
      - section: "F# 기초"
        contents:
          - notes/fsharp_01.qmd
          - notes/fsharp_02.qmd
          - notes/fsharp_03.qmd
          - notes/fsharp_04.qmd
          - notes/fsharp_05.qmd
          - notes/fsharp_06.qmd
          - notes/fsharp_07.qmd
          - notes/fsharp_08.qmd
          - notes/fsharp_09.qmd
          - notes/fsharp_10.qmd
          - notes/fsharp_11.qmd
          - notes/fsharp_12.qmd
          - notes/fsharp_13.qmd
          - notes/fsharp_14.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  # pdf:
  #   documentclass: article
  #   include-in-header:
  #     text: |
  #       \usepackage{kotex}