project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!slides/"
    - "!_ing"
  preview:
    port: 3000
    browser: false    

website:
  title: "F#"
  description: "Learn F# with MVP!"
  twitter-card: true
  open-graph: true
  page-navigation: true
  repo-branch: main
  repo-url: https://github.com/sigmadream/practice-fsharp
  repo-actions: [issue]  
  back-to-top-navigation: true
  page-footer: "Copyright 2024, Sangkon Han" 
  navbar:
    search: true
    right:      
      - icon: github
        href: https://github.com/sigmadream/practice-fsharp
  sidebar:
    style: "floating"

metadata-files:
  - sidebar.yml

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  # pdf:
  #   documentclass: article
  #   include-in-header:
  #     text: |
  #       \usepackage{kotex}
