---
title: "F# - 시작하기"
author: "Sangkon Han"
date: "2024-11-03"
categories: 
    - F#, 
    - .NET
---

개발자가 특정 언어를 선택하는 것은 프로젝트의 성패에 영향을 미치곤 합니다. 그러나 학습이나 재미를 위해서 혹은 효율이나 생산성과 전혀 관련없지만 '힙(hip)'한 어떤 것을 선택할 때가 있습니다. 불과 얼마전까지만 해도 학자들의 언어, 혹은 대학원생의 언어로 불렸던 `Haskell`, `Prolog` 같은 언어들이 [블럭체인](https://cardano.org/)이나 [머신러닝](https://arxiv.org/pdf/1805.10872) 등에 활용되고 있다는 것이 대표적인 예 입니다. 효율적인 데이터 처리와 정확한 계산에 대한 수요가 증가함에 따라 비효율적인 언어의 대명사처럼 알려진 함수형 언어에 대한 관심이 높아졌습니다. 함수형 언어는 가파른 학습 곡선으로 인해서 연구용 언어로 취급되었지만 지금은 많은 개발자들이 "효율"과 "안전"을 위해서 선택하기도 합니다. 함수형과 객체지향 프로그래밍 패러다임이 결합되어 나름의 장점을 뽐내는 방법을 고민하고 있습니다. 이를 통해 단순성, 효율성 그리고 안정성을 추구하기도 합니다.

새로운 프로그래밍 기법을 연습하기 위해서 `.NET` 플랫폼의 함수형 언어인 `F#`을 가볍게 배워볼 생각입니다. F#은 복잡한 작업을 간결하고 효과적으로 처리할 수 있을 뿐만 아니라, 개발 관련된 환경이 잘 구성되어 있습니다. F#을 활용해서 불변성, 일급 함수 등 함수형 언어가 제시하는 다양한 개념을 연습할 수 있도록 구성하였습니다. 이러한 연습 혹은 수련을 통해서 함수형 언어를 조금 쉽게 접근할 수 있기를 희망합니다.

F#을 선택한 이유는 .NET 환경과 원활한 통합입니다. .NET 플랫폼의 일부인 F#은 다양한 라이브러리 및 도구를 제공하기 때문에 Microsoft 기술 스택에 익숙한 개발자에게 완벽한 선택이 될 수 있습니다. F#은 함수형 프로그래밍에 관심이 있는 초급 개발자에서 기존의 중규모 서비스를 개선하기 위한 분들까지 배워볼만한 실용적인 언어라 할 수 있습니다. 혹은 그렇게 되길 희망합니다.
